{
 "title": "Wordpress",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "PID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "docker_container_status",
     "query": "SELECT \"container_id\" FROM \"docker_container_status\" WHERE (\"io.kubernetes.pod.name\" = 'wordpress') AND $timeFilter",
     "select": [
      [
       { "params": [ "pid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  },
  {
   "title": "Container Start Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "docker_container_status",
     "query": "SELECT \"container_id\" FROM \"docker_container_status\" WHERE (\"io.kubernetes.pod.name\" = 'wordpress') AND $timeFilter",
     "select": [
      [
       { "params": [ "started_at" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  },
  {
   "title": "Number of restarts And state Code",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT \"restarts_total\" FROM \"kubernetes_pod_container\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "restarts_total" ], "type": "field" }
      ],
      [
       { "params": [ "state_code" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  },
  {
   "title": "% CPU USAGE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  },
  {
   "title": "% MEMORY USAGE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "io.kubernetes.container.name", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  }
 ]
}