apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: ft-services
type: Opaque
data:
  db_name: d29yZHByZXNz
  db_user: cm9vdA== #admin
  db_password: cGFzc3dvcmQ= #password
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-pass
  namespace: ft-services
type: Opaque
data:
  INFLUXDB_CONFIG_PATH: L2V0Yy9pbmZsdXhkYi9pbmZsdXhkYi5jb25m #/etc/influxdb/influxdb.conf
  INFLUXDB_ADMIN_USER: YWRtaW4= #admin
  INFLUXDB_ADMIN_PASSWORD: YWRtaW4= #admin
  INFLUXDB_MONITORING_USER: dGVsZWdyYWY= #telegraf
  INFLUXDB_MONITORING_PASSWORD: dGVsZWdyYWY= #telegraf
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-pass
  namespace: ft-services
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: dGVsZWdyYWY= #telegraf
  GF_SECURITY_ADMIN_PASSWORD: dGVsZWdyYWY=
---
apiVersion: v1
kind: Secret
metadata:
  name: vsftpd-pass
  namespace: ft-services
type: Opaque
data:
   FTP_USER: dXNlcg== #user
   FTP_PASS: cGFzc3dvcmQ= #password
