apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: ft-services
  labels:
    app: mariadb
  annotations:
    metallb.universe.tf/allow-shared-ip: single-ip
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: ft-services
  labels:
    app: mariadb
  namespace: ft-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: ft-services
  labels:
    app: mariadb
  namespace: ft-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      restartPolicy: Always
      containers:
        - name: mariadb
          image: mariadb:local
          imagePullPolicy: Never
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-pass
                key: db_password
          ports:
          - containerPort: 3306
            name: mariadb
            protocol: TCP
          volumeMounts:
          - name: mariadb-pv
            mountPath: /var/lib/mysql
            subPath: mysql
  volumeClaimTemplates:
  - metadata:
      name: mariadb-pv
      namespace: ft-services
      labels:
        app: mariadb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
