apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: ft-services
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: single-ip
spec:
  type: LoadBalancer
  selector:
    app: wordpress
    tier: frontend
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  namespace: ft-services
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: ft-services
  labels:
    app: wordpress
    tier: frontend
  namespace: ft-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:local
        imagePullPolicy: Never
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb.ft-services.svc.cluster.local
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mariadb-pass
              key: db_name
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pass
              key: db_password
        ports:
        - containerPort: 5050
          name: wordpress
        volumeMounts:
        - name: wordpress-pv
          mountPath: /var/www/localhost/wordpress/storage
        #- name: nginx
        #  mountPath: /etc/nginx
        - name: wordpress-configmap
          mountPath: /var/www/localhost/wordpress/wp-config.php
          subPath: wp-config.php
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: wordpress-pv
        persistentVolumeClaim:
          claimName: wp-pvc
      - name: wordpress-configmap
        configMap:
          name: wordpress-configmap
